openapi: 3.0.0

info:
  title: Report Service API
  description: This server receives and stores PING results, and provides aggregated reports.
  version: 0.0.0

servers:
- url: http://{server-endpoint}/{api-version}
  description: report service server (internal)
  variables:
    server-endpoint:
      enum:
        - report-service-api
        - 127.0.0.1:8000
      default: 127.0.0.1:8000
    api-version:
      default: v1

paths:
  /health:
    get:
      description: the path for checking the API health
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: ok
  /results:
    post:
      description: the path for collecting PING results
      consumes:
        - application/json
      parameters:
        - in: body
          name: ping-result
          description: the ping result to store
          schema:
            type: object
            required:
              - url
              - utctime
              - status
            properties:
              url:
                description: pinged url (must be a valid url.)
                type: string
                example: https://kubernetes.io
              utctime:
                description: pinged time in UTC (YYYY-MM-DDThh:mm:ss.ssZ)
                type: string
                example: '1985-04-12T23:20:50.52Z'
              status:
                description: pinged status
                type: string
                enum: ['200', '300', '400', '500']
                example: '200'
              latency:
                description: the time taken for each ping investigation in millisecond (optional)
                type: number
                example: 1578
      responses:
        '201':
          description: created
        '400':
          description: bad request, input paramter error
          content:
            application/json:
              schema:
                type: object
                properties:
                  fieldname:
                    description: field-level validation error message
                    type: string
                example:
                  url: invalid url
                  utctime: invalid utc time format. must be of YYYY-MM-DDThh:mm:ss.ssZ
  /reports:
    get:
      description: the path to fetch ping reports for the certain period of time
      parameters:
        - in: query
          name: url
          required: true
          description: the url to fetch the report. must be url-encoded
          example: https%3A%2F%2Fkubernetes.io
          schema:
            type: string
        - in: query
          name: starttime
          required: true
          description: the start time in UTC of the report to fetch (YYYY-MM-DDThh:mm:ss.ssZ)
          example: '2018-05-01T23:20:50.52Z'
          schema:
            type: string
        - in: query
          name: endtime
          required: true
          description: the end time in UTC of the report to fetch (YYYY-MM-DDThh:mm:ss.ssZ)
          example: '2018-05-31T23:20:50.52Z'
          schema:
            type: string
      responses:
        '200':
          description: not specified yet
        '404':
          description: no report for the url
        '400':
          description: bad request, input paramter error
          content:
            application/json:
              schema:
                type: object
                properties:
                  fieldname:
                    description: field-level validation error message
                    type: string
                example:
                  url: invalid url
                  starttime: invalid utc time format. must be of YYYY-MM-DDThh:mm:ss.ssZ
